In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import EDA

In [2]:
tr = pd.read_pickle('../data/train.pkl')
te = pd.read_pickle('../data/test.pkl')
tr_log = pd.read_pickle('../data/train_log.pkl')
te_log = pd.read_pickle('../data/test_log00.pkl')

In [3]:
tr.head()

,object_id,ra,decl,gal_l,gal_b,ddf,hostgal_specz,hostgal_photoz,hostgal_photoz_err,distmod,mwebv,target
0,615,349.046051,-61.943836,320.796530,-51.753706,1,0.0000,0.0000,0.0000,NaN,0.017,92
1,713,53.085938,-27.784405,223.525509,-54.460748,1,1.8181,1.6267,0.2552,45.4063,0.007,88
2,730,33.574219,-6.579593,170.455585,-61.548219,1,0.2320,0.2262,0.0157,40.2561,0.021,42
3,745,0.189873,-45.586655,328.254458,-68.969298,1,0.3037,0.2813,1.1523,40.7951,0.007,90
4,1124,352.711273,-63.823658,316.922299,-51.059403,1,0.1934,0.2415,0.0176,40.4166,0.024,90

In [4]:
tr_log.head()

   object_id           mjd  passband        flux   flux_err  detected
0        615  59750.421875         2 -544.810303   3.622952         1
1        615  59750.429688         1 -816.434326   5.553370         1
2        615  59750.437500         3 -471.385529   3.801213         1
3        615  59750.445312         4 -388.984985  11.395031         1
4        615  59752.406250         2 -681.858887   4.041204         1

In [5]:
EDA.df_info(tr)

Shape: (7848, 12)

,DataType,#Nulls,#Uniques,Min,Mean,Max,Std,top10 val,top10 cnt,top10 raito
object_id,int64,0,7848,615.000000,4.810375e+07,1.307798e+08,4.347364e+07,"[78974, 50136410, 53935453, 110418764, 337180,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
ra,float64,0,3009,0.175781,1.697194e+02,3.598242e+02,1.142128e+02,"[33.574219, 150.820312, 52.91015600000001, 53....","[65, 64, 57, 57, 56, 53, 53, 52, 46, 45]","[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0..."
decl,float64,0,403,-64.760857,-2.725485e+01,4.181528e+00,2.024856e+01,"[-46.768478, -28.630989000000003, 3.583322, -2...","[94, 87, 70, 69, 69, 67, 66, 65, 62, 58]","[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0..."
gal_l,float64,0,5504,0.107681,2.304668e+02,3.599438e+02,9.741639e+01,"[223.280041, 321.472056, 236.341348, 319.54298...","[29, 28, 25, 25, 24, 23, 23, 23, 23, 22]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
gal_b,float64,0,5504,-89.615573,-2.011553e+01,6.593132e+01,4.039090e+01,"[-54.281374, -50.73533, -51.376556, 43.230123,...","[29, 28, 25, 25, 24, 23, 23, 23, 23, 22]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
ddf,int64,0,2,0.000000,2.696228e-01,1.000000e+00,4.437921e-01,"[0, 1]","[5732, 2116]","[0.73, 0.27]"
hostgal_specz,float64,0,3750,0.000000,2.544364e-01,3.445100e+00,3.300529e-01,"[0.0, 0.1703, 0.1145, 0.2517, 0.2524, 0.2367, ...","[2325, 6, 6, 6, 6, 6, 6, 5, 5, 5]","[0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
hostgal_photoz,float64,0,4025,0.000000,3.578845e-01,2.999400e+00,5.455516e-01,"[0.0, 0.1231, 0.1126, 0.1809, 0.2564, 0.1869, ...","[2325, 7, 7, 6, 6, 6, 5, 5, 5, 5]","[0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
hostgal_photoz_err,float64,0,2456,0.000000,1.556947e-01,1.734800e+00,3.003674e-01,"[0.0, 0.0143, 0.0148, 0.0132, 0.0164, 0.0125, ...","[2325, 24, 23, 23, 20, 20, 20, 20, 20, 20]","[0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
distmod,float64,2325,5300,31.996100,4.126396e+01,4.702560e+01,2.262711e+00,"[40.9868, 41.8773, 41.8196, 42.6063, 42.4889, ...","[4, 3, 3, 3, 3, 3, 3, 3, 3, 3]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
mwebv,float64,0,593,0.003000,8.195260e-02,2.747000e+00,1.505977e-01,"[0.019, 0.018000000000000002, 0.00900000000000...","[301, 275, 271, 240, 228, 206, 205, 194, 172, ...","[0.04, 0.04, 0.03, 0.03, 0.03, 0.03, 0.03, 0.0..."
target,int64,0,14,6.000000,6.089539e+01,9.500000e+01,2.876798e+01,"[90, 42, 65, 16, 15, 62, 88, 92, 67, 52]","[2313, 1193, 981, 924, 495, 484, 370, 239, 208...","[0.29, 0.15, 0.12, 0.12, 0.06, 0.06, 0.05, 0.0..."

In [6]:
EDA.df_info(te)

Shape: (3492890, 11)

,DataType,#Nulls,#Uniques,Min,Mean,Max,Std,top10 val,top10 cnt,top10 raito
object_id,int64,0,3492890,13.000000,6.528181e+07,1.307881e+08,3.783131e+07,"[67112958, 14507713, 81698346, 52340414, 22974...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
ra,float64,0,12811,0.000000,1.705897e+02,3.598242e+02,1.092068e+02,"[53.4375, 53.085938, 66.621094, 331.875, 26.89...","[2739, 2665, 2597, 2553, 2542, 2535, 2526, 248...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
decl,float64,0,404,-64.760857,-2.624964e+01,4.181528e+00,1.764381e+01,"[-21.702768, -30.865254999999998, -27.784405, ...","[12137, 12131, 11858, 11775, 11753, 11686, 116...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
gal_l,float64,0,50084,0.010369,2.178545e+02,3.599956e+02,1.081992e+02,"[326.278557, 329.485675, 327.956322, 328.53142...","[309, 306, 305, 294, 293, 291, 285, 282, 279, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
gal_b,float64,0,50081,-89.674414,-1.843280e+01,6.606870e+01,3.958926e+01,"[-69.858253, -69.15090500000001, -68.803772, -...","[309, 306, 305, 294, 293, 291, 285, 282, 279, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
ddf,int64,0,2,0.000000,9.426578e-03,1.000000e+00,9.663188e-02,"[0, 1]","[3459964, 32926]","[0.99, 0.01]"
hostgal_specz,float64,3372497,8052,0.007700,3.059878e-01,1.201400e+00,1.599283e-01,"[0.3099, 0.2555, 0.239, 0.2466, 0.2482, 0.3005...","[56, 50, 47, 46, 45, 45, 45, 44, 44, 43]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
hostgal_photoz,float64,0,29858,0.000000,5.168159e-01,3.000000e+00,4.491342e-01,"[0.0, 0.4481, 0.4787, 0.4541, 0.4659, 0.451, 0...","[390510, 566, 562, 559, 558, 557, 554, 554, 55...","[0.11, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
hostgal_photoz_err,float64,0,11103,0.000000,1.535211e-01,1.871400e+00,2.752581e-01,"[0.0, 0.0136, 0.0101, 0.01, 0.0175, 0.0095, 0....","[390510, 8264, 8208, 8061, 7857, 7830, 7824, 7...","[0.11, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
distmod,float64,390510,103633,27.646200,4.217862e+01,4.702610e+01,1.587242e+00,"[42.4333, 42.5537, 42.7395, 42.6734, 42.5592, ...","[135, 134, 134, 133, 133, 132, 132, 131, 131, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
mwebv,float64,0,1513,0.002000,9.196644e-02,2.994000e+00,1.551435e-01,"[0.012, 0.013000000000000001, 0.01399999999999...","[68973, 68425, 66001, 64031, 61940, 61537, 614...","[0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.0..."

In [7]:
tr[tr.hostgal_photoz==0]

,object_id,ra,decl,gal_l,gal_b,ddf,hostgal_specz,hostgal_photoz,hostgal_photoz_err,distmod,mwebv,target
0,615,349.046051,-61.943836,320.796530,-51.753706,1,0.0,0.0,0.0,NaN,0.017,92
5,1227,35.683594,-5.379379,171.992947,-59.253501,1,0.0,0.0,0.0,NaN,0.020,65
9,1926,149.414062,1.940072,236.565366,41.393323,1,0.0,0.0,0.0,NaN,0.018,65
14,2624,346.655182,-63.260487,320.952196,-50.040935,1,0.0,0.0,0.0,NaN,0.019,65
15,2677,53.964844,-28.630989,225.142950,-53.813613,1,0.0,0.0,0.0,NaN,0.009,16
24,4171,2.097458,-45.783966,324.737840,-69.478613,1,0.0,0.0,0.0,NaN,0.011,16
32,6266,0.929752,-44.597992,328.531426,-70.083244,1,0.0,0.0,0.0,NaN,0.011,65
39,7566,359.446716,-44.201530,331.730015,-69.805709,1,0.0,0.0,0.0,NaN,0.010,16
42,7756,149.414062,2.238686,236.239766,41.565558,1,0.0,0.0,0.0,NaN,0.017,16
44,8688,32.695312,-4.929937,166.868469,-60.841230,1,0.0,0.0,0.0,NaN,0.018,65
46,8784,34.101562,-5.829153,170.247753,-60.638325,1,0.0,0.0,0.0,NaN,0.019,16
47,9006,34.277344,-5.079716,169.526841,-59.956640,1,0.0,0.0,0.0,NaN,0.019,65
48,9172,346.655182,-63.260487,320.952196,-50.040935,1,0.0,0.0,0.0,NaN,0.019,65
51,9543,352.132874,-63.636005,317.424173,-51.095855,1,0.0,0.0,0.0,NaN,0.021,65
53,9985,150.820312,3.732834,235.666318,43.572109,1,0.0,0.0,0.0,NaN,0.016,65
56,10349,34.980469,-6.279288,172.180075,-60.389399,1,0.0,0.0,0.0,NaN,0.023,65
60,10796,52.910156,-25.944481,220.366350,-54.301439,1,0.0,0.0,0.0,NaN,0.010,65
62,11165,150.996094,2.985506,236.647967,43.287350,1,0.0,0.0,0.0,NaN,0.020,16
67,11931,149.589844,3.583322,234.885369,42.474696,1,0.0,0.0,0.0,NaN,0.024,65
69,12695,51.855469,-28.630989,224.733260,-55.649872,1,0.0,0.0,0.0,NaN,0.009,92
70,12872,347.861847,-61.943836,321.519104,-51.424048,1,0.0,0.0,0.0,NaN,0.017,65
77,14080,150.996094,4.181528,235.291975,43.970869,1,0.0,0.0,0.0,NaN,0.015,65
78,14156,53.085938,-27.111860,222.384291,-54.355086,1,0.0,0.0,0.0,NaN,0.007,65
88,15475,351.382965,-64.011238,317.574052,-50.604657,1,0.0,0.0,0.0,NaN,0.023,65
89,15626,346.130127,-63.072620,321.423103,-50.042305,1,0.0,0.0,0.0,NaN,0.020,16
91,15700,359.415588,-46.768478,327.729895,-67.686097,1,0.0,0.0,0.0,NaN,0.009,16
95,16339,51.328125,-27.447618,222.535046,-55.950727,1,0.0,0.0,0.0,NaN,0.013,16
96,16349,150.820312,3.134927,236.341348,43.230123,1,0.0,0.0,0.0,NaN,0.016,16
101,17094,52.207031,-28.291550,224.208534,-55.300157,1,0.0,0.0,0.0,NaN,0.007,16
102,17172,53.437500,-29.142223,225.908120,-54.336118,1,0.0,0.0,0.0,NaN,0.008,16
...,...,...,...,...,...,...,...,...,...,...,...,...
7760,128971260,111.269531,-0.895283,217.589784,7.066774,0,0.0,0.0,0.0,NaN,0.062,65
7761,128983448,172.089844,-11.719760,272.801095,46.234873,0,0.0,0.0,0.0,NaN,0.027,6
7767,129030512,167.695312,-2.238686,259.394755,51.914899,0,0.0,0.0,0.0,NaN,0.037,65
7769,129045287,101.250000,-30.172440,239.716771,-14.524251,0,0.0,0.0,0.0,NaN,0.102,65
7772,129135543,303.222656,-14.785930,28.282576,-24.570001,0,0.0,0.0,0.0,NaN,0.136,65
7777,129257128,53.728447,-46.571846,255.231725,-52.543327,0,0.0,0.0,0.0,NaN,0.008,65
7787,129399030,113.203125,-31.563116,245.510180,-5.884312,0,0.0,0.0,0.0,NaN,0.334,65
7788,129416892,156.269531,-2.686724,247.314667,43.822879,0,0.0,0.0,0.0,NaN,0.035,65
7789,129459169,120.761719,-0.596842,221.856842,15.593596,0,0.0,0.0,0.0,NaN,0.027,16
7796,129705825,265.000000,-47.945496,343.130199,-8.959896,0,0.0,0.0,0.0,NaN,0.211,16
7804,129845065,240.820312,-27.784405,346.739128,18.342981,0,0.0,0.0,0.0,NaN,0.180,16
7806,129937154,69.960938,-38.111038,241.144647,-41.435325,0,0.0,0.0,0.0,NaN,0.016,16
7807,129964738,185.625000,-38.111038,296.685212,24.409461,0,0.0,0.0,0.0,NaN,0.073,65
7809,130062639,106.875000,-39.257931,250.208713,-13.903969,0,0.0,0.0,0.0,NaN,0.126,16
7813,130102264,31.041668,-49.702389,276.078712,-63.462614,0,0.0,0.0,0.0,NaN,0.015,16
7815,130108924,254.179688,-19.313040,1.760188,14.612169,0,0.0,0.0,0.0,NaN,0.284,65
7818,130219752,355.163544,-50.091457,328.699808,-63.346833,0,0.0,0.0,0.0,NaN,0.013,6
7821,130312781,133.242188,-24.788561,249.573365,12.560887,0,0.0,0.0,0.0,NaN,0.131,16
7823,130330088,340.839844,-32.442867,14.265035,-61.816065,0,0.0,0.0,0.0,NaN,0.010,65
7826,130386135,28.828125,-25.117701,208.535318,-75.532469,0,0.0,0.0,0.0,NaN,0.011,65
7828,130408188,314.296875,-40.033035,2.071417,-40.445067,0,0.0,0.0,0.0,NaN,0.036,16
7830,130489916,209.707031,-38.300922,317.204568,22.695931,0,0.0,0.0,0.0,NaN,0.074,16
7834,130622528,132.539062,-1.641510,229.063354,25.304821,0,0.0,0.0,0.0,NaN,0.015,65
7838,130684460,117.949219,-0.895283,220.752608,12.975772,0,0.0,0.0,0.0,NaN,0.053,16
7841,130716752,337.372894,-57.209084,332.816119,-50.876643,0,0.0,0.0,0.0,NaN,0.016,16
7842,130727624,294.960938,-4.031936,34.856817,-12.602145,0,0.0,0.0,0.0,NaN,0.291,65
7843,130739978,26.718750,-14.940303,172.342697,-72.255675,0,0.0,0.0,0.0,NaN,0.013,65
7845,130762946,203.108109,-55.682144,308.728904,6.727511,0,0.0,0.0,0.0,NaN,0.430,16
7846,130772921,79.101562,-35.501846,239.172243,-33.827844,0,0.0,0.0,0.0,NaN,0.034,65
7847,130779836,301.992188,-17.426323,25.102988,-24.511101,0,0.0,0.0,0.0,NaN,0.091,6

In [8]:
te[te.hostgal_photoz==0]

,object_id,ra,decl,gal_l,gal_b,ddf,hostgal_specz,hostgal_photoz,hostgal_photoz_err,distmod,mwebv
20,168,349.429535,-62.508568,320.039643,-51.393745,1,NaN,0.0,0.0,NaN,0.020
115,1063,53.789062,-27.784405,223.685697,-53.845803,1,NaN,0.0,0.0,NaN,0.009
240,2270,151.171875,2.238686,237.619933,42.994783,1,NaN,0.0,0.0,NaN,0.024
279,2790,349.285706,-62.884678,319.786163,-51.046461,1,NaN,0.0,0.0,NaN,0.018
408,4025,33.222656,-4.780192,167.515653,-60.396584,1,NaN,0.0,0.0,NaN,0.018
417,4109,52.910156,-26.276812,220.926149,-54.363918,1,NaN,0.0,0.0,NaN,0.008
839,8442,351.953644,-62.132156,318.777388,-52.347124,1,NaN,0.0,0.0,NaN,0.019
895,8933,349.046051,-61.943836,320.796530,-51.753706,1,NaN,0.0,0.0,NaN,0.017
1070,10946,150.820312,1.641510,237.994507,42.358984,1,NaN,0.0,0.0,NaN,0.020
1149,11786,52.910156,-25.944481,220.366350,-54.301439,1,NaN,0.0,0.0,NaN,0.010
1325,13619,53.085938,-28.122234,224.100909,-54.509752,1,NaN,0.0,0.0,NaN,0.007
1390,14235,349.285706,-62.884678,319.786163,-51.046461,1,NaN,0.0,0.0,NaN,0.018
1461,14982,352.398651,-62.696659,318.017427,-51.967966,1,NaN,0.0,0.0,NaN,0.020
2441,25882,34.277344,-5.079716,169.526841,-59.956640,1,NaN,0.0,0.0,NaN,0.019
2462,26083,349.615387,-63.636005,318.927246,-50.506542,1,NaN,0.0,0.0,NaN,0.018
2686,28505,51.328125,-27.447618,222.535046,-55.950727,1,NaN,0.0,0.0,NaN,0.013
2803,29710,32.871094,-4.780192,166.959493,-60.615132,1,NaN,0.0,0.0,NaN,0.017
3073,32683,52.207031,-26.610098,221.298836,-55.042928,1,NaN,0.0,0.0,NaN,0.014
3335,35518,349.046051,-61.943836,320.796530,-51.753706,1,NaN,0.0,0.0,NaN,0.017
3414,36490,53.613281,-26.944359,222.237403,-53.863858,1,NaN,0.0,0.0,NaN,0.009
3617,38628,352.398651,-62.696659,318.017427,-51.967966,1,NaN,0.0,0.0,NaN,0.020
4282,45395,54.667969,-27.615883,223.610785,-53.050840,1,NaN,0.0,0.0,NaN,0.009
4506,47700,35.683594,-5.379379,171.992947,-59.253501,1,NaN,0.0,0.0,NaN,0.020
4526,47865,346.500000,-62.320400,321.951129,-50.736054,1,NaN,0.0,0.0,NaN,0.020
4628,48994,346.500000,-62.320400,321.951129,-50.736054,1,NaN,0.0,0.0,NaN,0.020
4641,49172,348.586945,-64.573555,318.693903,-49.477869,1,NaN,0.0,0.0,NaN,0.018
4654,49343,349.429535,-62.508568,320.039643,-51.393745,1,NaN,0.0,0.0,NaN,0.020
4918,52329,2.457983,-45.389202,324.632685,-69.945696,1,NaN,0.0,0.0,NaN,0.011
4967,52832,150.820312,1.641510,237.994507,42.358984,1,NaN,0.0,0.0,NaN,0.020
5139,54629,347.617462,-62.508568,321.121462,-50.904708,1,NaN,0.0,0.0,NaN,0.019
...,...,...,...,...,...,...,...,...,...,...,...
3492697,130780149,104.240509,-45.586655,255.535412,-18.101569,0,NaN,0.0,0.0,NaN,0.074
3492718,130780981,304.101562,-2.537361,40.616761,-20.018380,0,NaN,0.0,0.0,NaN,0.084
3492728,130781438,87.539062,-36.981888,242.614638,-27.525700,0,NaN,0.0,0.0,NaN,0.038
3492736,130781742,144.735580,-51.255806,275.153183,0.926067,0,NaN,0.0,0.0,NaN,1.693
3492740,130782018,101.250000,-8.234748,219.550857,-5.166457,0,NaN,0.0,0.0,NaN,0.552
3492744,130782103,337.500000,-1.044512,64.504909,-47.223633,0,NaN,0.0,0.0,NaN,0.052
3492746,130782265,145.898438,-25.117701,257.835865,20.880429,0,NaN,0.0,0.0,NaN,0.054
3492748,130782332,150.996094,-24.624317,261.174456,24.364409,0,NaN,0.0,0.0,NaN,0.042
3492750,130782378,340.903351,-45.389202,348.699193,-58.750748,0,NaN,0.0,0.0,NaN,0.009
3492756,130782563,135.000000,-50.674160,270.428222,-3.019471,0,NaN,0.0,0.0,NaN,1.401
3492761,130782827,307.949310,-49.507675,349.781935,-36.286896,0,NaN,0.0,0.0,NaN,0.028
3492763,130782960,140.625000,-15.249383,246.363880,23.949550,0,NaN,0.0,0.0,NaN,0.050
3492789,130784268,219.187500,-44.993881,321.790037,13.987061,0,NaN,0.0,0.0,NaN,0.135
3492796,130784509,56.155460,-45.389202,252.679006,-51.216637,0,NaN,0.0,0.0,NaN,0.006
3492805,130784903,92.062500,-44.993881,252.245122,-26.122830,0,NaN,0.0,0.0,NaN,0.083
3492809,130784975,275.328949,-47.357574,346.943719,-14.857000,0,NaN,0.0,0.0,NaN,0.075
3492815,130785118,121.113281,-6.880079,227.692270,12.834621,0,NaN,0.0,0.0,NaN,0.059
3492820,130785214,100.019531,-5.079716,216.170782,-4.835535,0,NaN,0.0,0.0,NaN,0.437
3492837,130785978,181.702698,-55.682144,296.626634,6.642308,0,NaN,0.0,0.0,NaN,0.351
3492841,130786129,97.031250,-31.914005,239.981080,-18.528007,0,NaN,0.0,0.0,NaN,0.045
3492842,130786184,196.384613,-53.764561,305.041057,9.049432,0,NaN,0.0,0.0,NaN,0.344
3492843,130786185,169.101562,-31.213543,280.094022,27.409528,0,NaN,0.0,0.0,NaN,0.056
3492844,130786299,169.628906,1.492246,258.033284,56.040179,0,NaN,0.0,0.0,NaN,0.041
3492850,130786756,76.627357,-50.480045,257.296344,-37.018658,0,NaN,0.0,0.0,NaN,0.012
3492864,130787315,47.017937,-48.336796,260.899075,-56.120132,0,NaN,0.0,0.0,NaN,0.015
3492868,130787553,119.882812,-31.213543,248.062371,-0.771655,0,NaN,0.0,0.0,NaN,0.817
3492872,130787746,232.382812,-21.542267,345.082356,28.107021,0,NaN,0.0,0.0,NaN,0.108
3492879,130787879,67.148438,-25.117701,223.472141,-41.599217,0,NaN,0.0,0.0,NaN,0.034
3492881,130787903,186.328125,-23.155577,295.162282,39.321709,0,NaN,0.0,0.0,NaN,0.055
3492882,130787932,244.863281,-19.155010,356.117330,21.588080,0,NaN,0.0,0.0,NaN,0.344